# Generated by Django 3.2.7 on 2021-10-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category_chile',
            fields=[
                ('catec_id', models.AutoField(primary_key=True, serialize=False)),
                ('catec_name', models.CharField(max_length=100)),
                ('catec_image', models.ImageField(upload_to='')),
                ('catep_id', models.IntegerField()),
                ('status', models.SmallIntegerField(choices=[(1, 'Hien thi'), (0, 'An')])),
                ('date_create', models.DateField()),
            ],
            options={
                'db_table': 'tb_CategoryChild',
            },
        ),
        migrations.CreateModel(
            name='Category_parent',
            fields=[
                ('catep_id', models.AutoField(primary_key=True, serialize=False)),
                ('catep_name', models.CharField(max_length=100)),
                ('status', models.SmallIntegerField(choices=[(1, 'Hien thi'), (0, 'An')])),
                ('date_create', models.DateField()),
            ],
            options={
                'db_table': 'tb_CategoryParent',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('catep_id', models.IntegerField()),
                ('catec_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=300)),
                ('product_image', models.ImageField(upload_to='')),
                ('pro_price', models.FloatField()),
                ('status', models.SmallIntegerField(choices=[(1, 'Hien thi'), (0, 'An')])),
                ('date_create', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
    ]
