# Generated by Django 3.2.7 on 2021-10-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_chile',
            name='catep_id',
            field=models.IntegerField(choices=[(1, 'Áo'), (2, 'Quần')]),
        ),
        migrations.AlterField(
            model_name='category_chile',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Con hang'), (0, 'Het hang')]),
        ),
        migrations.AlterField(
            model_name='category_parent',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Con hang'), (0, 'Het hang')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='catec_id',
            field=models.IntegerField(choices=[(1, 'Áo khoác'), (2, 'Áo sơ mi'), (3, 'Váy'), (4, 'Quần jean')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='catep_id',
            field=models.IntegerField(choices=[(1, 'Áo'), (2, 'Quần')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='pro_price',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Con hang'), (0, 'Het hang')]),
        ),
    ]
