# Generated by Django 3.2.7 on 2021-10-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_product_product_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_chile',
            name='catec_image',
            field=models.ImageField(null='true', upload_to=''),
        ),
        migrations.AlterField(
            model_name='category_chile',
            name='catep_id',
            field=models.IntegerField(choices=[(1, 'Áo'), (2, 'Quần'), (3, 'Gìay'), (4, 'Phụ kiện'), (5, 'Đồ bộ')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='catec_id',
            field=models.IntegerField(choices=[(1, 'Áo khoác'), (2, 'Áo sơ mi'), (4, 'Quần jean')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='catep_id',
            field=models.IntegerField(choices=[(1, 'Áo'), (2, 'Quần'), (3, 'Gìay'), (4, 'Phụ kiện'), (5, 'Đồ bộ')]),
        ),
    ]
