# Generated by Django 3.2.7 on 2021-10-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category_chile',
            name='status',
        ),
        migrations.RemoveField(
            model_name='category_parent',
            name='status',
        ),
        migrations.AddField(
            model_name='product',
            name='promotion',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Hết hàng'), (1, 'Sale'), (2, 'Mới')]),
        ),
    ]
