# Generated by Django 3.2.7 on 2021-10-28 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20211028_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='promotion',
        ),
    ]
