# Generated by Django 3.2.7 on 2021-10-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_product_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='promotion',
            field=models.SmallIntegerField(choices=[(0, 'Bình thường'), (1, 'Nổi bật')], default=0),
        ),
    ]
